---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    ethereum:
      hosts:

        lighthouse.consensus.ethereum.mainnet.encapsulate.xyz:
          type: consensus
          client: lighthouse

        nethermind.execution.ethereum.mainnet.encapsulate.xyz:
          type: execution
          client: nethermind

        prysm.consensus.ethereum.mainnet.encapsulate.xyz:
          type: consensus
          client: prysm

        geth.execution.ethereum.mainnet.encapsulate.xyz:
          type: execution
          client: geth

        arid.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost

        manta.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost

        zephyr.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost

    ssv:
      hosts:

        arid_ssv_node_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: node
          cluster: arid

        arid_ssv_dkg_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: dkg
          cluster: arid

        manta_ssv_node_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: node
          cluster: manta

        manta_ssv_dkg_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: dkg
          cluster: manta

    obol:
      hosts:

        zephyr_obol_charon_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: charon
          cluster: zephyr

        zephyr_obol_ejector_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: ejector
          cluster: zephyr
          obol_dv_exit_message_dir: /opt/obol-dv-exit-{{ cluster }}/data

        zephyr_obol_dv_exit_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: dv_exit
          cluster: zephyr
          charon_run_time_dir: /opt/obol-charon-{{ cluster }}/key

        zephyr_obol_lodestar_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: lodestar
          cluster: zephyr
