---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    ethereum:
      hosts:
        arid_consensus_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: lighthouse
          cluster: arid
        arid_execution_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: nethermind
          cluster: arid

        manta_consensus_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: lighthouse
          cluster: manta
        manta_execution_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: nethermind
          cluster: manta

        zypher_consensus_client:
          ansible_host: zypher.validator.ethereum.mainnet.encapsulate.xyz
          type: prysm
          cluster: zypher
        zypher_execution_client:
          ansible_host: zypher.validator.ethereum.mainnet.encapsulate.xyz
          type: geth
          cluster: zypher
