---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    ethereum:
      hosts:

        lighthouse.consensus.ethereum.mainnet.encapsulate.xyz:
          type: consensus
          client: lighthouse
          network: mainnet
          checkpoint_sync_url: "https://beaconstate.info"

        nethermind.execution.ethereum.mainnet.encapsulate.xyz:
          type: execution
          client: nethermind
          genesis_hash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"

        prysm.consensus.ethereum.mainnet.encapsulate.xyz:
          type: consensus
          client: prysm

        geth.execution.ethereum.mainnet.encapsulate.xyz:
          type: execution
          client: geth

        lighthouse.mevboost.ethereum.mainnet.encapsulate.xyz:
          client: lighthouse
          type: mevboost

        prysm.mevboost.ethereum.mainnet.encapsulate.xyz:
          client: prysm
          type: mevboost

    ssv:
      hosts:

        arid.node.ssv.mainnet.encapsulate.xyz:
          type: node
          cluster: arid

        arid.dkg.ssv.mainnet.encapsulate.xyz:
          type: dkg
          cluster: arid

        manta.node.ssv.mainnet.encapsulate.xyz:
          type: node
          cluster: manta

        manta.dkg.ssv.mainnet.encapsulate.xyz:
          type: dkg
          cluster: manta

    obol:
      hosts:

        zephyr.charon.obol.mainnet.encapsulate.xyz:
          type: charon
          cluster: zephyr

        zephyr.ejector.obol.mainnet.encapsulate.xyz:
          type: ejector
          cluster: zephyr
          obol_dv_exit_message_dir: /opt/obol-dv-exit-{{ cluster }}/data

        zephyr.dvexit.obol.mainnet.encapsulate.xyz:
          type: dv_exit
          cluster: zephyr
          charon_run_time_dir: /opt/obol-charon-{{ cluster }}/key

        zephyr.lodestar.obol.mainnet.encapsulate.xyz:
          type: lodestar
          cluster: zephyr
