---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    ethereum:
      hosts:

        lighthouse.consensus.ethereum.mainnet.encapsulate.xyz:
          type: cons
          client: lighthouse
          network: mainnet
          checkpoint_sync_url: "https://beaconstate.info"

        nethermind.execution.ethereum.mainnet.encapsulate.xyz:
          type: exec
          client: nethermind
          network: mainnet
          genesis_hash: "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3"

        ts.prysm.consensus.ethereum.mainnet.encapsulate.xyz:
          type: cons
          network: mainnet
          client: prysm

        ts.geth.execution.ethereum.mainnet.encapsulate.xyz:
          type: exec
          network: mainnet
          client: geth

        lighthouse.mevboost.ethereum.mainnet.encapsulate.xyz:
          client: lighthouse
          network: mainnet
          type: mev

        ts.prysm.mevboost.ethereum.mainnet.encapsulate.xyz:
          client: prysm
          network: mainnet
          type: mev

    ssv:
      hosts:

        ts.arid.node.ssv.mainnet.encapsulate.xyz:
          type: node
          cluster: arid

        ts.arid.dkg.ssv.mainnet.encapsulate.xyz:
          type: dkg
          cluster: arid

        ts.manta.node.ssv.mainnet.encapsulate.xyz:
          type: node
          cluster: manta

        ts.manta.dkg.ssv.mainnet.encapsulate.xyz:
          type: dkg
          cluster: manta

    obol:
      hosts:

        ts.zephyr.charon.obol.mainnet.encapsulate.xyz:
          type: charon
          cluster: zephyr
          cluster_name: "Zephyr Zorilla"
          cluster_peer: "cloudy-game"
          discord_id: "1288506628852809728,1336898516668252260"

        ts.zephyr.ejector.obol.mainnet.encapsulate.xyz:
          type: ejector
          cluster: zephyr
          obol_dv_exit_message_dir: /opt/obol-dv-exit-{{ cluster }}/data

        ts.zephyr.dvexit.obol.mainnet.encapsulate.xyz:
          type: dv_exit
          cluster: zephyr
          charon_run_time_dir: /opt/obol-charon-{{ cluster }}/key

        ts.zephyr.lodestar.obol.mainnet.encapsulate.xyz:
          type: lodestar
          cluster: zephyr
