---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    ethereum:
      hosts:

        arid_consensus_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: consensus
          client: lighthouse

        arid_execution_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: consensus
          client: nethermind

        manta_consensus_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: consensus
          client: lighthouse

        manta_execution_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: execution
          client: nethermind

        zypher_consensus_client:
          ansible_host: zypher.validator.ethereum.mainnet.encapsulate.xyz
          type: consensus
          client: prysm

        zypher_execution_client:
          ansible_host: zypher.validator.ethereum.mainnet.encapsulate.xyz
          type: execution
          client: geth

        arid.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost
        manta.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost
        zypher.validator.ethereum.mainnet.encapsulate.xyz:
          type: mev_boost

    ssv:
      hosts:

        arid_ssv_node_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: node
          cluster: arid

        arid_ssv_dkg_client:
          ansible_host: arid.validator.ethereum.mainnet.encapsulate.xyz
          type: dkg
          cluster: arid

        manta_ssv_node_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: node
          cluster: manta

        manta_ssv_dkg_client:
          ansible_host: manta.validator.ethereum.mainnet.encapsulate.xyz
          type: dkg
          cluster: manta

    obol:
      hosts:

        zephyr_obol_charon_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: charon
          cluster: zephyr

        zephyr_obol_ejector_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: ejector
          cluster: zephyr

        zephyr_obol_dv_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: dv
          cluster: zephyr

        zephyr_obol_lodestar_client:
          ansible_host: zephyr.validator.ethereum.mainnet.encapsulate.xyz
          type: lodestar
          cluster: zephyr
