---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    ethereum:
      hosts:

        lighthouse.consensus.ethereum.hoodi.encapsulate.xyz:
          type: consensus
          client: lighthouse
          network: hoodi
          checkpoint_sync_url: "https://checkpoint-sync.hoodi.ethpandaops.io"

        nethermind.execution.ethereum.hoodi.encapsulate.xyz:
          type: execution
          client: nethermind
          network: hoodi
          genesis_hash: "0xbbe312868b376a3001692a646dd2d7d1e4406380dfd86b98aa8a34d1557c971b"

        lighthouse.mevboost.ethereum.hoodi.encapsulate.xyz:
          client: lighthouse
          type: mevboost
        
        lighthouse.consensus.ethereum.sepolia.encapsulate.xyz:
          type: consensus
          client: lighthouse
          network: sepolia
          checkpoint_sync_url: "https://checkpoint-sync.sepolia.ethpandaops.io"
        
        nethermind.execution.ethereum.sepolia.encapsulate.xyz:
          type: execution
          client: nethermind
          network: sepolia
          genesis_hash: "0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf5138993e6dd9"

        lighthouse.mevboost.ethereum.sepolia.encapsulate.xyz:
          client: lighthouse
          type: mevboost

        lighthouse_sepolia_host:
          ansible_host: 65.109.158.204
          type: consensus
          client: lighthouse
          network: sepolia
          checkpoint_sync_url: "https://checkpoint-sync.sepolia.ethpandaops.io"

        nethermind_sepolia_host:
          ansible_host: 65.109.158.204
          type: execution
          client: nethermind
          network: sepolia
          genesis_hash: "0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf5138993e6dd9"

        mevboost_sepolia_host:
          ansible_host: 65.109.158.204
          client: lighthouse
          type: mevboost

    obol:
      hosts:

        primev.charon.obol.testnet.encapsulate.xyz:
          type: charon
          cluster: primev

        primev.lodestar.obol.testnet.encapsulate.xyz:
          type: lodestar
          cluster: primev
