---
- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ obol_dv_exit_home_dir }}"
    directories: "{{ obol_dv_exit_directories }}"
    log_file_path: "{{ obol_dv_exit_log_file_path }}"

- name: Include build binary task
  ansible.builtin.include_tasks: build_binary.yml

- name: Copy general environment file
  ansible.builtin.template:
    src: "{{ cluster }}/{{ env }}/general.env.j2"
    dest: "{{ obol_dv_exit_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart service

- name: Copy obol dv client systemd service file
  ansible.builtin.template:
    src: "{{ cluster }}/{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
