---
prysm_ufw_rules:
  - port: "{{ ethereum.prysm.ports.p2p_tcp }}"
    proto: tcp
    rule: allow
    from: any
    comment: prysm_p2p_tcp_port

  - port: "{{ ethereum.prysm.ports.p2p_udp }}"
    proto: udp
    rule: allow
    from: any
    comment: prysm_p2p_udp_port

  - port: "{{ ethereum.prysm.ports.quic }}"
    proto: udp
    rule: allow
    from: any
    comment: prysm_quic_port

  - port: "{{ ethereum.prysm.ports.metrics }}"
    proto: tcp
    rule: allow
    from: "{{ monitor_server_dns }}"
    comment: prysm_metrics_port

  - port: "{{ ethereum.prysm.ports.http }}"
    proto: tcp
    rule: allow
    from: "manta.node.ssv.mainnet.encapsulate.xyz"
    comment: prysm_http_port

  - port: "{{ ethereum.prysm.ports.http }}"
    proto: tcp
    rule: allow
    from: "arid.node.ssv.mainnet.encapsulate.xyz"
    comment: prysm_http_port

  - port: "{{ ethereum.prysm.ports.http }}"
    proto: tcp
    rule: allow
    from: "zephyr.charon.obol.mainnet.encapsulate.xyz"
    comment: prysm_http_port
