---
- name: Include the ufw rules vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ prysm_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ prysm_home_dir }}"
    directories: "{{ prysm_directories }}"
    log_file_path: "{{ prysm_log_file_path }}"

- name: Include extract binary task
  ansible.builtin.include_tasks: download_binary.yml

- name: Save jwtsecret
  ansible.builtin.template:
    src: jwtsecret.j2
    dest: "{{ prysm_jwt_secret_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Copy prysm client systemd service file
  ansible.builtin.template:
    src: "{{ env }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
