---
- name: Include the ufw rules vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ geth_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ geth_home_dir }}"
    directories: "{{ geth_directories }}"
    log_file_path: "{{ geth_log_file_path }}"

- name: Include extract binary task
  ansible.builtin.include_tasks: extract_binary.yml

- name: Save jwtsecret
  ansible.builtin.template:
    src: jwtsecret.j2
    dest: "{{ geth_jwt_secret_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Copy env file
  ansible.builtin.template:
    src: "{{ cluster }}/general.env.j2"
    dest: "{{ geth_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart service

- name: Copy geth client systemd service file
  ansible.builtin.template:
    src: "{{ cluster }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
