---
- name: Copy import keys script
  ansible.builtin.template:
    src: import_keys.sh.j2
    dest: "{{ tmp_dir }}/import_keys.sh"
    owner: root
    group: root
    mode: "0755"

- name: Run import keys script
  ansible.builtin.shell: "{{ tmp_dir }}/import_keys.sh"
  changed_when: import_keys
  notify:
    - Restart service

- name: Delete import keys script
  ansible.builtin.file:
    path: "{{ tmp_dir }}/import_keys.sh"
    state: absent

- name: Set ownership for secret and key directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true
  loop: 
    - "{{ obol_lodestar_key_dir }}"
    - "{{ obol_lodestar_secret_dir }}"
