---
- name: Include the ufw rules vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ obol_lodestar_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ obol_lodestar_home_dir }}"
    directories: "{{ obol_lodestar_directories }}"
    log_file_path: "{{ obol_lodestar_log_file_path }}"

- name: Include extract binary task
  ansible.builtin.include_tasks: extract_binary.yml

- name: Include import_keys task
  ansible.builtin.include_tasks: import_keys.yml
  when: import_keys | default(false) | bool

- name: Copy obol lodestar client systemd service file
  ansible.builtin.template:
    src: "{{ env }}/{{ cluster }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
